<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="110" started-at="2018-04-12T06:51:33Z" finished-at="2018-04-12T06:51:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="110" started-at="2018-04-12T06:51:33Z" finished-at="2018-04-12T06:51:33Z">
      <class name="com.aditya.homePage.TestNGTest">
        <test-method status="PASS" signature="Firstmethod()[pri:0, instance:com.aditya.homePage.TestNGTest@7a3d45bd]" name="Firstmethod" duration-ms="28" started-at="2018-04-12T06:51:33Z" finished-at="2018-04-12T06:51:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Firstmethod -->
        <test-method status="SKIP" signature="Secondmethod()[pri:0, instance:com.aditya.homePage.TestNGTest@7a3d45bd]" name="Secondmethod" duration-ms="7" started-at="2018-04-12T06:51:33Z" finished-at="2018-04-12T06:51:33Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Not Matched]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Not Matched
at com.aditya.homePage.TestNGTest.Secondmethod(TestNGTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Secondmethod -->
      </class> <!-- com.aditya.homePage.TestNGTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
